config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static_pages#home'
  namespace :admin do
    root 'static_pages#home'

    resources :galleries
    resources :images
    resources :sheets
  end
  namespace :en do
    root 'static_pages#home'
    resources :galleries
    resources :images
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/gallery.rb
class Gallery < ApplicationRecord
  include Paperclip::Glue

  has_attached_file :photo, styles: { big: "800x600>", medium: "400x300>", small: "100x75>" }
  validates_attachment_content_type :photo, content_type: /\Aimage\/.*\z/
  validates :photo, attachment_presence: true
end

app/models/image.rb
class Image < ApplicationRecord
  include Paperclip::Glue
  has_attached_file :photo, styles: { big: "1920x785>", medium: "1920x600>", small: "100x75>" }
  validates_attachment_content_type :photo, content_type: /\Aimage\/.*\z/
  validates :photo, attachment_presence: true
end

app/models/sheet.rb
class Sheet < ApplicationRecord
end

app/controllers/admin/application_controller.rb
class Admin::ApplicationController < ApplicationController

    before_action :authenticate

    protected

    def authenticate
      authenticate_or_request_with_http_basic do |username, password|
        username == "admin" && password == "admin"
    end
  end
end

app/controllers/admin/galleries_controller.rb
class Admin::GalleriesController < Admin::ApplicationController
  def index
    @galleries = Gallery.all
  end
  def new
    @gallery = Gallery.new
  end
  def edit
  @gallery = Gallery.find(params[:id])
  end
  def create
    @gallery = Gallery.new(gallery_params)
    if @gallery.save
      redirect_to admin_galleries_path
    else
      render :new
    end
  end
  def update
    @gallery = Gallery.find(params[:id])
    if @gallery.update(gallery_params)
    redirect_to admin_galleries_path
    else
    render 'edit'
    end
  end
  def destroy
  @gallery = Gallery.find(params[:id])
  @gallery.destroy
  redirect_to admin_galleries_path
  end
  private
  def gallery_params
    params.require(:gallery).permit(:text, :photo)
  end
end

app/controllers/admin/images_controller.rb
class Admin::ImagesController < Admin::ApplicationController
  def index
    @images = Image.all
  end
  def new
    @image = Image.new
  end
  def edit
  @image = Image.find(params[:id])
  end
  def create
    @image = Image.new(image_params)
    if @image.save
      redirect_to admin_images_path
    else
      render :new
    end
  end
  def update
    @image = Image.find(params[:id])
    if @image.update(image_params)
    redirect_to admin_images_path
    else
    render 'edit'
    end
  end
  def destroy
  @image = Image.find(params[:id])
  @image.destroy
  redirect_to admin_images_path
  end
  private
  def image_params
    params.require(:image).permit(:text, :photo)
  end
end

app/controllers/admin/sheets_controller.rb
class Admin::SheetsController < Admin::ApplicationController
  def index
    @sheets = Sheet.all
  end
  def new
    @sheet = Sheet.new
  end
  def edit
  @sheet = Sheet.find(params[:id])
  end
  def create
    @sheet = Sheet.new(sheet_params)
    if @sheet.save
      redirect_to admin_sheets_path
    else
      render :new
    end
  end
  def update
    @sheet = Sheet.find(params[:id])
    if @sheet.update(sheet_params)
    redirect_to admin_sheets_path
    else
    render 'edit'
    end
  end
  def destroy
  @sheet = Sheet.find(params[:id])
  @sheet.destroy
  redirect_to admin_sheets_path
  end
  private
  def sheet_params
    params.require(:sheet).permit(:text)
  end
end

app/controllers/admin/static_pages_controller.rb
class Admin::StaticPagesController < Admin::ApplicationController
  def home
    @galleries = Gallery.all
    @images = Image.all
    @sheets = Sheet.all
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @galleries = Gallery.all
    @images = Image.all
    @sheets = Sheet.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/galleries/edit.html.erb
<% if @gallery.errors.present? %>
  <%= @gallery.errors.full_messages%>
<% end %>

<%= form_for [:admin, @gallery], html: { multipart: true } do |form| %>
  <div class="form-group">
  <%= form.text_area :text %>
  <%= form.file_field :photo %>
  <%= form.submit 'Сохранить', class: 'btn btn-default'%>
    </div>
<% end %>

app/views/admin/galleries/galleries/edit.html.erb
<% if @gallery.errors.present? %>
  <%= @gallery.errors.full_messages%>
<% end %>

<%= form_for [:admin, @gallery], html: { multipart: true } do |form| %>
  <div class="form-group">
  <%= form.text_area :text %>
  <%= form.file_field :photo %>
  <%= form.submit 'Сохранить', class: 'btn btn-default'%>
    </div>
<% end %>

app/views/admin/galleries/galleries/index.html.erb
<%= link_to 'Создать', new_admin_gallery_path, class: 'btn btn-default' %>
<table class="table">
  <thead>
    <tr>
      <th>Photo</th>
      <th>Text</th>
      <th>Item</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @galleries.each do |gallery| %>
      <tr>
        <td>
          <%= image_tag gallery.photo.url(:medium) %>
        </td>
        <td>
          <%= gallery.text %>
        </td>
        <td>
          <%= link_to 'Редактировать', edit_admin_gallery_path(gallery), class: 'btn btn-default' %></td>
        </td>
        <td>
          <%= link_to 'Удалить', admin_gallery_path(gallery), class: 'btn btn-default',
          method: :delete,
          data: { confirm: 'Продолжить?' } %>
        </td>
    </tr>
    <% end %>
  </tbody>

app/views/admin/galleries/galleries/new.html.erb
<% if @gallery.errors.present? %>
  <%= @gallery.errors.full_messages%>
<% end %>

<%= form_for [:admin, @gallery], html: { multipart: true } do |form| %>
  <div class="form-group">

  <%= form.text_area :text %>
  <%= form.file_field :photo, class: 'form-control' %>
  <%= form.submit 'Создать', class: 'btn btn-default'%>
  </div>
<% end %>

app/views/admin/galleries/index.html.erb
<%= link_to 'Создать', new_admin_gallery_path, class: 'btn btn-default' %>
<table class="table">
  <thead>
    <tr>
      <th>Photo</th>
      <th>Text</th>
      <th>Item</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @galleries.each do |gallery| %>
      <tr>
        <td>
          <%= image_tag gallery.photo.url(:medium) %>
        </td>
        <td>
          <%= gallery.text %>
        </td>
        <td>
          <%= link_to 'Редактировать', edit_admin_gallery_path(gallery), class: 'btn btn-default' %></td>
        </td>
        <td>
          <%= link_to 'Удалить', admin_gallery_path(gallery), class: 'btn btn-default',
          method: :delete,
          data: { confirm: 'Продолжить?' } %>
        </td>
    </tr>
    <% end %>
  </tbody>

app/views/admin/galleries/new.html.erb
<% if @gallery.errors.present? %>
  <%= @gallery.errors.full_messages%>
<% end %>

<%= form_for [:admin, @gallery], html: { multipart: true } do |form| %>
  <div class="form-group">

  <%= form.text_area :text %>
  <%= form.file_field :photo, class: 'form-control' %>
  <%= form.submit 'Создать', class: 'btn btn-default'%>
  </div>
<% end %>

app/views/admin/images/edit.html.erb
<% if @image.errors.present? %>
  <%= @image.errors.full_messages%>
<% end %>

<%= form_for [:admin, @image], html: { multipart: true } do |form| %>
  <div class="form-group">
  <%= form.text_area :text %>
  <%= form.file_field :photo %>
  <%= form.submit 'Сохранить', class: 'btn btn-default'%>
    </div>
<% end %>

app/views/admin/images/index.html.erb
<%= link_to 'Создать', new_admin_image_path, class: 'btn btn-default' %>
<table class="table">
  <thead>
    <tr>
      <th>Photo</th>
      <th>Text</th>
      <th>Item</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @images.each do |image| %>
      <tr>
        <td>
          <%= image_tag image.photo.url(:small) %>
        </td>
        <td>
          <%= image.text %>
        </td>
        <td>
          <%= link_to 'Редактировать', edit_admin_image_path(image), class: 'btn btn-default' %></td>
        </td>
        <td>
          <%= link_to 'Удалить', admin_image_path(image), class: 'btn btn-default',
          method: :delete,
          data: { confirm: 'Продолжить?' } %>
        </td>
    </tr>
    <% end %>
  </tbody>

app/views/admin/images/new.html.erb
<% if @image.errors.present? %>
  <%= @image.errors.full_messages%>
<% end %>

<%= form_for [:admin, @image], html: { multipart: true } do |form| %>
  <div class="form-group">

  <%= form.text_area :text %>
  <%= form.file_field :photo, class: 'form-control' %>
  <%= form.submit 'Создать', class: 'btn btn-default'%>
  </div>
<% end %>

app/views/admin/sheets/edit.html.erb
<% if @sheet.errors.present? %>
  <%= @sheet.errors.full_messages%>
<% end %>

<%= form_for [:admin, @sheet], html: { multipart: true } do |form| %>
  <div class="form-group">
  <%= form.text_area :text, :class => "tinymce", :rows => 40, :cols => 120 %>
   <%= tinymce %>
  <%= form.submit 'Сохранить', class: 'btn btn-default'%>
    </div>
<% end %>

app/views/admin/sheets/index.html.erb
<%= link_to 'Создать', new_admin_sheet_path, class: 'btn btn-default' %>
<table class="table">
  <thead>
    <tr>
      <th>Text</th>
      <th>Item</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @sheets.each do |sheet| %>
      <tr>
        <td>
          <%= sheet.text %>
        </td>
        <td>
          <%= link_to 'Редактировать', edit_admin_sheet_path(sheet), class: 'btn btn-default' %></td>
        </td>
        <td>
          <%= link_to 'Удалить', admin_sheet_path(sheet), class: 'btn btn-default',
          method: :delete,
          data: { confirm: 'Продолжить?' } %>
        </td>
    </tr>
    <% end %>
  </tbody>

app/views/admin/sheets/new.html.erb
<% if @sheet.errors.present? %>
  <%= @sheet.errors.full_messages%>
<% end %>

<%= form_for [:admin, @sheet], html: { multipart: true } do |form| %>
  <div class="form-group">

  <%= form.text_area :text %>
  <%= form.submit 'Создать', class: 'btn btn-default'%>
  </div>
<% end %>

app/views/admin/static_pages/home.html.erb
<div class="container-fluid">


    <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
    <li data-target="#carousel-example-generic" data-slide-to="1"></li>
    <li data-target="#carousel-example-generic" data-slide-to="2"></li>
    <li data-target="#carousel-example-generic" data-slide-to="3"></li>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner" role="listbox">
    <div class="item active">
      <% @images.where(id:1).each do |image| %>
          <%= image_tag image.photo.url(:big) %>
          <%= link_to 'Редактировать',edit_admin_image_path(image), class: 'btn btn-default centr' %>
      <div class="carousel-caption">
        <h2>  <%= image.text %> </h2>
          <%= link_to 'Редактировать',edit_admin_image_path(image), class: 'btn btn-default' %>
        <%end %>
      </div>
    </div>
    <div class="item">
      <% @images.where(id:2).each do |image| %>
          <%= image_tag image.photo.url(:big) %>
          <%= link_to 'Редактировать',edit_admin_image_path(image), class: 'btn btn-default' %>
      <div class="carousel-caption">
        <h2>  <%= image.text %> </h2>
          <%= link_to 'Редактировать',edit_admin_image_path(image), class: 'btn btn-default' %>
        <%end %>
      </div>
    </div>
    <div class="item">
      <% @images.where(id:3).each do |image| %>
          <%= image_tag image.photo.url(:big) %>
          <%= link_to 'Редактировать',edit_admin_image_path(image), class: 'btn btn-default' %>
      <div class="carousel-caption">
        <h2>  <%= image.text %> </h2>
          <%= link_to 'Редактировать',edit_admin_image_path(image), class: 'btn btn-default' %>
        <%end %>
      </div>
    </div>
    <div class="item">
      <% @images.where(id:4).each do |image| %>
          <%= image_tag image.photo.url(:big) %>
          <%= link_to 'Редактировать',edit_admin_image_path(image), class: 'btn btn-default' %>
          <div class="carousel-caption">
          <h2>  <%= image.text %> </h2>
          <%= link_to 'Редактировать',edit_admin_image_path(image), class: 'btn btn-default' %>
          <%end %>
      </div>
    </div>
  </div>

  <!-- Controls -->
</div>

<!-- Отеле -->

<% @sheets.where(id:2).each do |gallery| %>
<p>  <%= gallery.text.html_safe %> </p>
<%= link_to 'Редактировать',edit_admin_sheet_path(gallery), class: 'btn btn-default centr' %>
<% end %>

<!-- Комнаты -->

<div class="container-fluid">
  <div class="rooms">
    <div class="row">
      <div class="col-md-6">
        <h2>Стандарт</h2>
        <div class="col-md-6">
              <% @images.where(id:5).each do |gallery| %>
                        <%= link_to gallery.photo.url(:big), :"data-fresco-group" => "room1",:"data-fresco-caption" => gallery.text, class: 'fresco' do %>
                        <%= image_tag gallery.photo.url(:medium), alt: 'nordplan', class: 'img-responsive' %>
                        <%= link_to 'Редактировать',edit_admin_image_path(gallery), class: 'btn btn-default' %>
                        <% end %>
                        <% end %>
                      </div>
                      <div class="col-md-6">
                        <p> <% @sheets.where(id:3).each do |gallery| %>
                        <%= gallery.text.html_safe %>
                        <%= link_to 'Редактировать',edit_admin_sheet_path(gallery), class: 'btn btn-default' %>
                        <% end %> </p>
                      </div>
                      <div class="">
                          <% @images.where(id:6).each do |gallery| %>
                          <%= link_to gallery.photo.url(:big), :"data-fresco-group" => "room1",:"data-fresco-caption" => gallery.text, class: 'fresco' do %>
                          <%= image_tag gallery.photo.url(:medium), alt: 'nordplan', class: 'image-size' %>
                          <% end %>
                          <% end %>
                          <% @images.where(id:7).each do |gallery| %>
                          <%= link_to gallery.photo.url(:big), :"data-fresco-group" => "room1",:"data-fresco-caption" => gallery.text, class: 'fresco' do %>
                          <%= image_tag gallery.photo.url(:medium), alt: 'nordplan', class: 'image-size' %>
                          <% end %>
                          <% end %>
                          <% @images.where(id:8).each do |gallery| %>
                          <%= link_to gallery.photo.url(:big), :"data-fresco-group" => "room1",:"data-fresco-caption" => gallery.text, class: 'fresco' do %>
                          <%= image_tag gallery.photo.url(:medium), alt: 'nordplan', class: 'image-size' %>
                          <% end %>
                          <% end %>
                          <% @images.where(id:9).each do |gallery| %>
                          <%= link_to gallery.photo.url(:big), :"data-fresco-group" => "room1",:"data-fresco-caption" => gallery.text, class: 'fresco' do %>
                          <%= image_tag gallery.photo.url(:medium), alt: 'nordplan', class: 'image-size' %>
                          <% end %>
                          <% end %>
                          <% @images.where(id:10).each do |gallery| %>
                          <%= link_to gallery.photo.url(:big), :"data-fresco-group" => "room1",:"data-fresco-caption" => gallery.text, class: 'fresco' do %>
                          <%= image_tag gallery.photo.url(:medium), alt: 'nordplan', class: 'image-size' %>
                          <% end %>
                          <% end %>
                          <% @images.where(id:11).each do |gallery| %>
                          <%= link_to gallery.photo.url(:big), :"data-fresco-group" => "room1",:"data-fresco-caption" => gallery.text, class: 'fresco' do %>
                          <%= image_tag gallery.photo.url(:medium), alt: 'nordplan', class: 'image-size' %>
                          <% end %>
                          <% end %>
                        </div>
                      </div>
                      <div class="col-md-6">
                        <h2>Комфорт</h2>
                        <div class="col-md-6">
                          <% @images.where(id:12).each do |gallery| %>
                          <%= link_to gallery.photo.url(:big), :"data-fresco-group" => "room2",:"data-fresco-caption" => gallery.text, class: 'fresco' do %>
                          <%= image_tag gallery.photo.url(:medium), alt: 'nordplan', class: 'img-responsive' %>
                          <%= link_to 'Редактировать',edit_admin_image_path(gallery), class: 'btn btn-default' %>
                          <% end %>
                          <% end %>
                        </div>
                        <div class="col-md-6">
                          <p> <% @sheets.where(id:4).each do |gallery| %>
                          <%= gallery.text.html_safe %>
                          <%= link_to 'Редактировать',edit_admin_sheet_path(gallery), class: 'btn btn-default centr' %>
                          <% end %> </p>
                          </div>
                          <div class="">
                            <% @images.where(id:13).each do |gallery| %>
                            <%= link_to gallery.photo.url(:big), :"data-fresco-group" => "room2",:"data-fresco-caption" => gallery.text, class: 'fresco' do %>
                            <%= image_tag gallery.photo.url(:medium), alt: 'nordplan', class: 'image-size' %>
                            <% end %>
                            <% end %>
                            <% @images.where(id:14).each do |gallery| %>
                            <%= link_to gallery.photo.url(:big), :"data-fresco-group" => "room2",:"data-fresco-caption" => gallery.text, class: 'fresco' do %>
                            <%= image_tag gallery.photo.url(:medium), alt: 'nordplan' , class: 'image-size' %>
                            <% end %>
                            <% end %>
                            <% @images.where(id:15).each do |gallery| %>
                            <%= link_to gallery.photo.url(:big), :"data-fresco-group" => "room2",:"data-fresco-caption" => gallery.text, class: 'fresco' do %>
                            <%= image_tag gallery.photo.url(:medium), alt: 'nordplan', class: 'image-size' %>
                            <% end %>
                            <% end %>
                            <% @images.where(id:16).each do |gallery| %>
                            <%= link_to gallery.photo.url(:big), :"data-fresco-group" => "room2",:"data-fresco-caption" => gallery.text, class: 'fresco' do %>
                            <%= image_tag gallery.photo.url(:medium), alt: 'nordplan', class: 'image-size' %>
                            <% end %>
                            <% end %>
                            <% @images.where(id:17).each do |gallery| %>
                            <%= link_to gallery.photo.url(:big), :"data-fresco-group" => "room2",:"data-fresco-caption" => gallery.text, class: 'fresco' do %>
                            <%= image_tag gallery.photo.url(:medium), alt: 'nordplan' , class: 'image-size' %>
                            <% end %>
                            <% end %>
                            <% @images.where(id:18).each do |gallery| %>
                            <%= link_to gallery.photo.url(:big), :"data-fresco-group" => "room2",:"data-fresco-caption" => gallery.text, class: 'fresco' do %>
                            <%= image_tag gallery.photo.url(:medium), alt: 'nordplan', class: 'image-size' %>
                            <% end %>
                            <% end %>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>

<div id="map" style="width: 100%; height: 400px" class="main"></div>

<div class="contacts main">
  <% @sheets.where(id:1).each do |gallery| %>
  <p>  <%= gallery.text.html_safe %> </p>
  <%= link_to 'Редактировать',edit_admin_sheet_path(gallery), class: 'btn btn-default centr' %>
<% end %>
</div>

</div>

app/views/layouts/admin/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Forteinn</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://fonts.googleapis.com/css?family=PT+Sans|Rubik|Ubuntu+Mono&display=swap" rel="stylesheet">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://api-maps.yandex.ru/2.1/?apikey=2c47806b-0f92-4034-90c9-047f883c400c&lang=ru_RU" type="text/javascript"></script>

  </head>

  <body>
    <div class="container">
      <nav class="navbar navbar-default">
        <div class="container-fluid">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">Настройки</a>
          </div>
            <div id="navbar" class="navbar-collapse collapse">
              <ul class="nav navbar-nav">
              <li>
                <%= active_link_to 'На сайт', root_path, active: :exact, wrap_tag: :li %>
              </li>
              <li>
                <%= active_link_to 'Галерея', '/admin/galleries', wrap_tag: :li %>
              </li>
              <li>
                <%= active_link_to 'Картинки', '/admin/images', wrap_tag: :li %>
              </li>
            </ul>
          </div>
        </div>
      </nav>

    <%= yield %>
  </body>
</html>